/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import LidhjaMeDatabaz.LidhjaDB;
import Modelet_Tabelat.Adresat;
import Modelet_Tabelat.KontaktetEKompanis;
import Modelet_Tabelat.KontaktetEPuntorve;
import Modelet_Tabelat.TeDhenatEpuntorve_tbl;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Vhaliti
 */
public class TeDhenatEPuntorve extends javax.swing.JFrame {

    /**
     * Creates new form TeDhenatEPuntorve
     */
    public TeDhenatEPuntorve() throws ParseException {
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        trego_Puntoret();
        trego_kontaktetEPuntorve();
        ikonaProgramit();
    }
    private void ikonaProgramit() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon48.png")));
    }
    String gjinia="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. 
     */
    @SuppressWarnings("unchecked")
//    ------------------------------------------------------------
        public void pastro(){
        emri.setText("");
        mbiemri.setText("");
        nrLeternjoftimit.setText("");
        String a="";
        ((JTextComponent)dataLindjes.getDateEditor().getUiComponent()).setText("");
        statusi.setSelectedIndex(0);
        adresaID.setText("");
        Adresa1.setText("");
        id.setText("");
        nrTelefonit.setText("");
        email.setText("");
        filter2.setText("");
        filterRruga2.setText("");
        buttonGroup1.clearSelection();
        
        
        }
//    -------------------------------------------------------------

   public boolean ekzistonsSiShfrytzues(String shfrytzus){
        try{
	 Connection con = LidhjaDB.ConnectDB();	
												
            String sql= "Select puntoriID from tbl_Shfrytzuesi";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
		if(shfrytzus.equals(rs.getString("puntoriID"))){
                    return true;
                }	
            }	
            return false;
	}
	catch(SQLException e){
		JOptionPane.showMessageDialog(null,e);
        }		
        return false;
    }
     public ArrayList<TeDhenatEpuntorve_tbl> puntoretEKompanisList(){
        ArrayList<TeDhenatEpuntorve_tbl> teDhenatList = new ArrayList<>();
         try{
            Connection con = LidhjaDB.ConnectDB();
            String query1=" SELECT n.puntoriID,n.emri,n.mbiemri, n.nrLeternjoftimit, n.gjinia,n.statusi,n.dataLindjes, tbl_Adresat.shteti,tbl_Adresat.qyteti,tbl_Adresat.rruga\n" +
            "FROM tbl_Puntori n\n" +
            "INNER JOIN tbl_Adresat ON n.adresaID = tbl_Adresat.adresaID";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            TeDhenatEpuntorve_tbl teDhenatK;
            while(rs.next()){
                teDhenatK = new TeDhenatEpuntorve_tbl(rs.getInt("puntoriID"), rs.getString("emri"),rs.getString("mbiemri"),rs.getInt("nrLeternjoftimit"),rs.getString("gjinia"),rs.getString("statusi"),rs.getString("dataLindjes"),rs.getString("shteti"),rs.getString("qyteti"),rs.getString("rruga"));
                teDhenatList.add(teDhenatK);
            }
         }catch (HeadlessException | SQLException e) {
          JOptionPane.showMessageDialog(null,e); 
        }
         return teDhenatList;
    }

        public void trego_Puntoret() throws ParseException{
        ArrayList<TeDhenatEpuntorve_tbl> list = puntoretEKompanisList();
        DefaultTableModel model = (DefaultTableModel)tbl1.getModel();
        Object[] row = new Object[10];
        DateFormat dateFormat = new SimpleDateFormat("yyyy");
        DateFormat dateFormat1 = new SimpleDateFormat("MM");
        DateFormat dateFormat2 = new SimpleDateFormat("dd");
        Date Viti = new Date();
        Date Muaji = new Date();
        Date Dita = new Date();

        String viti= dateFormat.format(Viti); 
        String muaji= dateFormat1.format(Muaji); 
        String dita= dateFormat2.format(Dita); 
//            String dateFromDateChooser = list.get(0).getDataLindjes();    
//            Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(dateFromDateChooser);
//            String date2=String.format("%1$tY", date1);
//            String date3=String.format("%1$tm", date1);
//            String date12 = String.format("%1$td", date1);
//            int DitaB1 = Integer.parseInt(date12);
//            int sum = DitaB1 + 2;
//            String numberAsString = Integer.toString(sum);
//            String a12 = (date2+"-"+date3+"-"+numberAsString);
//            Date date02=new SimpleDateFormat("yyyy-mm-dd").parse(a12);
//            DateFormat formatter = new SimpleDateFormat("yyyy-mm-dd");
//            String today = formatter.format(date02);
//            jTextField1.setText(today);
            
 
        for(int i =0;i<list.size();i++){
            String ktheDatenNeString = list.get(i).getDataLindjes();    
            Date kompletData=new SimpleDateFormat("yyyy-MM-dd").parse(ktheDatenNeString);
            String dataViti=String.format("%1$tY", kompletData);
            String dataMuaji=String.format("%1$tm", kompletData);
            String dataDita = String.format("%1$td", kompletData);
            int KtheDitenNeNumer = Integer.parseInt(dataDita);
            int ShtoDit = KtheDitenNeNumer + 2;
            String DitetEshtuaraString = Integer.toString(ShtoDit);
            String dataRe = (dataViti+"-"+dataMuaji+"-"+DitetEshtuaraString);
            Date date02=new SimpleDateFormat("yyyy-mm-dd").parse(dataRe);
            DateFormat formatter = new SimpleDateFormat("yyyy-mm-dd");
            String DataRregullume = formatter.format(date02);

            row[0]=list.get(i).getID();
            row[1]=list.get(i).getEmri();
            row[2]=list.get(i).getMbiemri();
            row[3]=list.get(i).getNrLeternjoftimit();
            row[4]=list.get(i).getGjinia();
            row[5]=list.get(i).getStatusi();
            row[6]=DataRregullume;
            row[7]= list.get(i).getShteti();
            row[8]=list.get(i).getQyteti();
            row[9]=list.get(i).getRruga();   

            model.addRow(row);
        }
         String countIKonvertuar = Integer.toString(list.size());
         mesazhZ.setText(countIKonvertuar);
    }
//     -----------------------------------------------------------------------------------------------
     public ArrayList<Adresat> adresatList(String a,String b){
        ArrayList<Adresat> teDhenatList = new ArrayList<>();
         try{
            Connection con = LidhjaDB.ConnectDB();
            String query1=" SELECT * FROM tbl_Adresat";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            Adresat teDhenatA;
            while(rs.next()){
                 if(a.equals(rs.getString("qyteti")) && b.equals(rs.getString("rruga")) || a.equals("!@#") && b.equals("#@!")){
                     teDhenatA = new Adresat(rs.getInt("adresaID"), rs.getString("shteti"),rs.getString("qyteti"),rs.getInt("zipcode"),rs.getString("rruga"), rs.getInt("nrRruges"));
                     teDhenatList.add(teDhenatA);
                }
                else if(a.equals(rs.getString("qyteti")) || b.equals(rs.getString("rruga"))){
                    teDhenatA = new Adresat(rs.getInt("adresaID"), rs.getString("shteti"),rs.getString("qyteti"),rs.getInt("zipcode"),rs.getString("rruga"), rs.getInt("nrRruges"));
                    teDhenatList.add(teDhenatA);
                }
            }
        if(teDhenatList.size() == 0){
                JOptionPane.showMessageDialog(null,"Kjo Adres nuk u gjend ne Databaz");
                
            }
         }catch (HeadlessException | SQLException e) {
          JOptionPane.showMessageDialog(null,e); 
        }
         return teDhenatList;
    }
 
    public final void trego_adresat(String a, String b){
        ArrayList<Adresat> list = adresatList(a,b);
        DefaultTableModel model = (DefaultTableModel)tbl4.getModel();
        Object[] row = new Object[6];
        for(int i =0;i<list.size();i++)
        {
            row[0]=list.get(i).getID();
            row[1]= list.get(i).getShteti();
            row[2]= list.get(i).getQyteti();
            row[3]= list.get(i).getZipCode();
            row[4]= list.get(i).getRruga();
            row[5]= list.get(i).getNrRruges();         
            model.addRow(row);
        }
    }
//    ---------------------------------------------------------------------------
    public ArrayList<KontaktetEPuntorve> kontaktetEPuntorveList(){
        ArrayList<KontaktetEPuntorve> teDhenatList = new ArrayList<>();
         try{
            Connection con = LidhjaDB.ConnectDB();
            String query1="SELECT n.kontaktiID,n.telefoni,n.email, tbl_Puntori.emri,tbl_Puntori.mbiemri,tbl_Puntori.gjinia\n" +
            "FROM Kontaktet_Puntori n\n" +
            "INNER JOIN tbl_Puntori ON n.puntoriID = tbl_Puntori.puntoriID";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            KontaktetEPuntorve teDhenatK;
            while(rs.next()){
                teDhenatK = new KontaktetEPuntorve(rs.getInt("kontaktiID"), rs.getString("telefoni"),rs.getString("email"),rs.getString("emri"),rs.getString("mbiemri"),rs.getString("gjinia"));
                teDhenatList.add(teDhenatK);
            }
         }catch (HeadlessException | SQLException e) {
          JOptionPane.showMessageDialog(null,e); 
        }
         return teDhenatList;
    }
//-------------------------------------------------
        public void trego_kontaktetEPuntorve(){
        ArrayList<KontaktetEPuntorve> list = kontaktetEPuntorveList();
        DefaultTableModel model = (DefaultTableModel)tbl2.getModel();
        Object[] row = new Object[6];
        for(int i =0;i<list.size();i++){
            row[0]=list.get(i).getID();
            row[1]=list.get(i).getEmri1();
            row[2]=list.get(i).getMbiemri1();
            row[3]=list.get(i).getGjinia1();
            row[4]= list.get(i).getTelefoni();
            row[5]= list.get(i).getEmaili();        
            model.addRow(row);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        emri = new javax.swing.JTextField();
        nrLeternjoftimit = new javax.swing.JTextField();
        adresaID = new javax.swing.JTextField();
        M = new javax.swing.JRadioButton();
        F = new javax.swing.JRadioButton();
        statusi = new javax.swing.JComboBox<>();
        dataLindjes = new com.toedter.calendar.JDateChooser();
        mbiemri = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        filter2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        filterRruga2 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl4 = new javax.swing.JTable();
        sh = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        nrTelefonit = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mesazhZ = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        Adresa1 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();

        setTitle("Regjistrimi i të dhënave të puntorëve");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Regjistrimi i të dëenave të puntorve"));

        jLabel1.setText("Emri");

        jLabel2.setText("Data e Lindjes");

        jLabel4.setText("Nr Leternjoftimit");

        jLabel5.setText("Gjinia");

        jLabel6.setText("Statusi");

        jLabel7.setText("Id e adreses");

        nrLeternjoftimit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nrLeternjoftimitKeyTyped(evt);
            }
        });

        adresaID.setEnabled(false);
        adresaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresaIDActionPerformed(evt);
            }
        });
        adresaID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adresaIDKeyTyped(evt);
            }
        });

        buttonGroup1.add(M);
        M.setText("Mashkull");

        buttonGroup1.add(F);
        F.setText("Femer");

        statusi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zgjidh Statusin", "I Martuar", "I PaMartuar", "" }));

        dataLindjes.setDateFormatString("yyyy-mm-dd");

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setText("Kerko sipas qytetit");

        filter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter2ActionPerformed(evt);
            }
        });

        jLabel15.setText("Kerko sipas Rruges");

        jButton12.setText("Search");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Pastro tabelen");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        tbl4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Shteti", "Qyteti", "ZipCode", "Rruga", "NrRruges"
            }
        ));
        tbl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl4);

        sh.setText("ALL");
        sh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filter2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterRruga2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sh)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(filter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(filterRruga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12)
                    .addComponent(jButton13)
                    .addComponent(sh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Regjistrimi kontakteve të puntorit"));

        jButton14.setText("Ruaje");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Fshije");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        id.setEnabled(false);

        jLabel18.setText("Id e puntorit në databaz");

        jLabel16.setText("Numri Telefonit");

        jLabel17.setText("Email ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton15)
                    .addComponent(nrTelefonit, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(email)
                    .addComponent(id))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrTelefonit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(jButton14))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Ruaje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Permirso");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Anulo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Shto Adres");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Fshije");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Dalje");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Autorizimet");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Numri puntorve ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("të regjistruar");

        mesazhZ.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        mesazhZ.setForeground(new java.awt.Color(255, 51, 51));
        mesazhZ.setText("jLabel6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mesazhZ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mesazhZ)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel3.setText("Mbiemri");

        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Emri", "Mbiemri", "Gjinia", "nr Telefonit", "Emaili"
            }
        ));
        tbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl2);

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Emri", "Mbiemri", "nrLeternjoftimit", "Gjinia", "Statusi", "DataLindjes", "Shteti", "Qyteti", "Rruga"
            }
        ));
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl1);

        Adresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adresa1ActionPerformed(evt);
            }
        });

        jButton8.setText("Vështro kontaktet");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(dataLindjes, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(emri, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(nrLeternjoftimit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(statusi, 0, 127, Short.MAX_VALUE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(M)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(F))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(mbiemri))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(adresaID, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Adresa1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(emri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(nrLeternjoftimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(M)
                                    .addComponent(F))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(dataLindjes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(statusi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(adresaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Adresa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(361, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(120, 120, 120)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        hide();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ShtoShfrytezues sh = new ShtoShfrytezues();
        sh.setVisible(true);
        hide();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{ 
             Connection con = LidhjaDB.ConnectDB();	
             String query ="insert into tbl_Puntori(emri,mbiemri,nrLeternjoftimit,gjinia,statusi,dataLindjes,adresaID)values(?,?,?,?,?,?,?)";
             PreparedStatement pst = con.prepareStatement(query);
            if(M.isSelected()){
                gjinia="Mashkull";
            }
            else if(F.isSelected()){
                gjinia="Femer";
            }            
            if(emri.getText().equals("")){
               JOptionPane.showMessageDialog( this, "Plotso emrin e puntorit","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);
            }
            else if(mbiemri.getText().equals("")){
              JOptionPane.showMessageDialog( this, "Plotso mbiemrin e puntorit","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);
            }
            else if(dataLindjes.getDate() == null ){
               JOptionPane.showMessageDialog( this, "Plotso rubriken e datlindja e puntorit","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);            
            }
            
             else if(nrLeternjoftimit.getText().equals("")){
               JOptionPane.showMessageDialog( this, "Plotso rubriken e leternjoftimi i punotrit","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);
            }
            else if(statusi.getSelectedItem().toString().equals("Zgjidh Statusin")){
               JOptionPane.showMessageDialog( this, "Cakto Statusin e puntorit","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);
            }
            else if(adresaID.getText().equals("")){
                JOptionPane.showMessageDialog( this, "Selektoni adresen e puntorit ne tabel","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);
                DefaultTableModel model = (DefaultTableModel) tbl4.getModel();
                model.setRowCount(0);
                trego_adresat("!@#","#@!");
                sh.setEnabled(false);
            
            }
             else{
                pst.setString(1,emri.getText());
                pst.setString(2,mbiemri.getText());
                pst.setString(3,nrLeternjoftimit.getText());
                pst.setString(4, gjinia);
                String statusi1;
                statusi1=statusi.getSelectedItem().toString();   
                statusi1=statusi.getSelectedItem().toString();
                pst.setString(5, statusi1);
                pst.setString(6,((JTextComponent)dataLindjes.getDateEditor().getUiComponent()).getText());
                pst.setString(7,adresaID.getText());
                pst.executeUpdate();
                DefaultTableModel model = (DefaultTableModel)tbl1.getModel();
                model.setRowCount(0);
                trego_Puntoret();
                JOptionPane.showMessageDialog(null,"U rexhistru me sukses!");
                pastro();
            }
                }catch (HeadlessException | SQLException e) {
          JOptionPane.showMessageDialog(null,e);
        } catch (ParseException ex) {
            Logger.getLogger(TeDhenatEPuntorve.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            int row = tbl1.getSelectedRow();
            if(tbl1.getSelectedRow() == -1){
                    JOptionPane.showMessageDialog(this ,"Ju nuk mund te Editoni asnje te dhene nese nuk e selektoni!","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);             
            }
            else{
                Connection con = LidhjaDB.ConnectDB();
                String IdESelektuar = (tbl1.getModel().getValueAt(row, 0).toString());
                String query ="UPDATE tbl_Puntori SET emri=?,mbiemri=?,nrLeternjoftimit=?,gjinia=?,statusi=?,dataLindjes=?,adresaID=? where puntoriID="+IdESelektuar;
                PreparedStatement pst = con.prepareStatement(query);
                
                if(emri.getText().equals("")){
                   JOptionPane.showMessageDialog( this, "Plotso emrin e puntorit","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);
                }
                else if(mbiemri.getText().equals("")){
                  JOptionPane.showMessageDialog( this, "Plotso mbiemrin e puntorit","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);
                }
                else if(((JTextComponent)dataLindjes.getDateEditor().getUiComponent()).getText().equals("")){
                   JOptionPane.showMessageDialog( this, "Plotso rubriken e datlindja e puntorit","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);            
                }

                 else if(nrLeternjoftimit.getText().equals("")){
                   JOptionPane.showMessageDialog( this, "Plotso rubriken e leternjoftimi i punotrit","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);
                }
                else if(statusi.getSelectedItem().toString().equals("Zgjidh Statusin")){
                   JOptionPane.showMessageDialog( this, "Cakto Statusin e puntorit","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);
                }

                else if(adresaID.getText().equals("")){
                   JOptionPane.showMessageDialog( this, "Perzgjidh adresen","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);   
                    DefaultTableModel model = (DefaultTableModel) tbl4.getModel();
                    model.setRowCount(0);
                    trego_adresat("!@#","#@!");
                    sh.setEnabled(false);
                }
                else{
                    pst.setString(1,emri.getText());
                    pst.setString(2,mbiemri.getText());
                    pst.setString(3,nrLeternjoftimit.getText());
                    pst.setString(4, gjinia);
                    String statusi1;
                    statusi1=statusi.getSelectedItem().toString();   
                    pst.setString(5, statusi1);
                    pst.setString(6,((JTextComponent)dataLindjes.getDateEditor().getUiComponent()).getText());
                    pst.setString(7,adresaID.getText());
                    pst.executeUpdate();
                    DefaultTableModel model = (DefaultTableModel)tbl1.getModel();
                    model.setRowCount(0);
                    trego_Puntoret();
                    trego_kontaktetEPuntorve();
                    JOptionPane.showMessageDialog(this ,"E dhena u editua me sukses","Informim", JOptionPane.INFORMATION_MESSAGE); 
                    pastro();
                }
            }
        } catch (HeadlessException | SQLException e) {
          JOptionPane.showMessageDialog(null,e); 
        } catch (ParseException ex) {
            Logger.getLogger(TeDhenatEPuntorve.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl2MouseClicked
   
    }//GEN-LAST:event_tbl2MouseClicked

    private void tbl4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl4MouseClicked
        int i = tbl4.getSelectedRow();
        TableModel model = tbl4.getModel();
        adresaID.setText(model.getValueAt(i,0).toString());
        Adresa1.setText("Shteti:"+model.getValueAt(i,1).toString()+", Qyteti:"+model.getValueAt(i,2).toString()+", Rruga:"+model.getValueAt(i,4).toString());
    }//GEN-LAST:event_tbl4MouseClicked

    private void filter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter2ActionPerformed

    }//GEN-LAST:event_filter2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
     if(filter2.getText().equals("") && filterRruga2.getText().equals("")){
            JOptionPane.showMessageDialog( this, "Nuk mund të bëni search nese nuk shkruani se qfar po kërkoni","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);
        }
        else{
            DefaultTableModel model = (DefaultTableModel) tbl4.getModel();
            model.setRowCount(0);
            trego_adresat(filter2.getText(),filterRruga2.getText());
            filter2.setText("");
            filterRruga2.setText("");
            sh.setEnabled(true);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
          DefaultTableModel model = (DefaultTableModel) tbl4.getModel();
        model.setRowCount(0);
        sh.setEnabled(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        try{
            Connection con = LidhjaDB.ConnectDB();
            String query ="insert into Kontaktet_Puntori(telefoni,email,puntoriID)values(?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
           
            if(id.getText().equals("")){
                JOptionPane.showMessageDialog( this, "Selektoni kompanin tek tabela","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);
            }
            else if(nrTelefonit.getText().equals("")){
                JOptionPane.showMessageDialog( this, "Shkruaje numrin e telefonit","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);
            }
            else if(email.getText().equals("")){
                JOptionPane.showMessageDialog( this, "Shkruaj emailin","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);
            }
            else if(!email.getText().contains("@")){
                JOptionPane.showMessageDialog( this, "Një email duhet te permbaj @!","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);
            }
            else{
                pst.setString(1,nrTelefonit.getText());
                pst.setString(2,email.getText());
                pst.setString(3,id.getText());

                pst.executeUpdate();
                DefaultTableModel model = (DefaultTableModel)tbl2.getModel();
                model.setRowCount(0);

                trego_kontaktetEPuntorve();
                JOptionPane.showMessageDialog(null,"Kontakti për puntorin "+emri.getText()+" u regjistrua");
                nrTelefonit.setText("");
                email.setText("");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        try{
            int row = tbl2.getSelectedRow();

            if(tbl2.getSelectedRow() == -1){
                JOptionPane.showMessageDialog(this ,"Ju nuk mund te fshini asnje kontakt nese nuk e selektoni!","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);
            }
            else{
                Object [] ob = {"Po","Jo"};
                int p = javax.swing.JOptionPane.showOptionDialog(this, "A jeni i sigurt se deshironi ta fshini pas fshirjes nuk ka me kthim te shenimeve ?", "Konfirmim", JOptionPane.OK_OPTION,JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);

                if (p==0){
                    Connection con = LidhjaDB.ConnectDB();
                    String IdESelektuar = (tbl2.getModel().getValueAt(row, 0).toString());
                    String query = "DELETE FROM Kontaktet_Puntori where kontaktiID="+IdESelektuar;
                    PreparedStatement pst = con.prepareStatement(query);
                    pst.executeUpdate();
                    DefaultTableModel model = (DefaultTableModel)tbl2.getModel();
                    model.setRowCount(0);
                    trego_kontaktetEPuntorve();
                    JOptionPane.showMessageDialog(this ,"E dhena u fshi me sukses","Informim", JOptionPane.INFORMATION_MESSAGE);
//                    pastro();
                }
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
        int i = tbl1.getSelectedRow();
       TableModel model = tbl1.getModel();
       id.setText(model.getValueAt(i,0).toString());
       emri.setText(model.getValueAt(i,1).toString());
       mbiemri.setText(model.getValueAt(i,2).toString());
       nrLeternjoftimit.setText(model.getValueAt(i, 3).toString());
       String a1 = model.getValueAt(i,4).toString();
       if(a1.equals("Mashkull")){
           M.setSelected(true);
       }
       else{
           F.setSelected(true);
       }
       
      
       String subject1 = model.getValueAt(i,5).toString();
       switch(subject1){
            case "Privilegjet":
            statusi.setSelectedIndex(0);
            break;
            case "I Martuar":
            statusi.setSelectedIndex(1);
            break;
            case "I PaMartuar":
            statusi.setSelectedIndex(2);
            break;
        }
        ((JTextComponent)dataLindjes.getDateEditor().getUiComponent()).setText(model.getValueAt(i, 6).toString());
         filter2.setText(model.getValueAt(i, 8).toString());
         filterRruga2.setText(model.getValueAt(i, 9).toString());      
    }//GEN-LAST:event_tbl1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         try{
            int row = tbl1.getSelectedRow();
            
            if(tbl1.getSelectedRow() == -1){
                    JOptionPane.showMessageDialog(this ,"Ju nuk mund te fshini asnje shfrytezues nese nuk e selektoni!","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);             
            }
            else{
                String IdESelektuar = (tbl1.getModel().getValueAt(row, 0).toString());
               
                if(ekzistonsSiShfrytzues(IdESelektuar)){
                        JOptionPane.showMessageDialog(this ,"Ky puntor nuk mund te fshihet ngesa ekziston si shfrytzues me par duhet hekur si shfrytzues pastaj te fshihet si puntor!","Mesazh nga Autori", JOptionPane.ERROR_MESSAGE);             

                }
                else{
                    Object [] ob = {"Po","Jo"};
                    int p = javax.swing.JOptionPane.showOptionDialog(this, "A jeni i sigurt se deshironi ta fshini pas fshirjes nuk ka me kthim te shenimeve, me fshirjen e puntorit fshihen dhe kontaktet e tij ?", "Konfirmim", JOptionPane.OK_OPTION,JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
            
                    if (p==0){
                    Connection con = LidhjaDB.ConnectDB();
//                    String IdESelektuar = (tbl1.getModel().getValueAt(row, 0).toString());
                    String query = "DELETE FROM tbl_Puntori where puntoriID="+IdESelektuar;
                    String query1 = "DELETE FROM Kontaktet_Puntori where puntoriID="+IdESelektuar;
                    PreparedStatement pst1 = con.prepareStatement(query1);
                    pst1.executeUpdate();
                    PreparedStatement pst = con.prepareStatement(query);
                    pst.executeUpdate();
                    DefaultTableModel model = (DefaultTableModel)tbl1.getModel();
                    model.setRowCount(0);
                    DefaultTableModel model1 = (DefaultTableModel)tbl2.getModel();
                    model1.setRowCount(0);
                    trego_kontaktetEPuntorve();
                    trego_Puntoret();
                    JOptionPane.showMessageDialog(this ,"E dhena u fshi me sukses","Informim", JOptionPane.INFORMATION_MESSAGE);
                    pastro(); 
                    }
                    }
                }            
            } catch (HeadlessException | SQLException e) {
          JOptionPane.showMessageDialog(null,e); 
        } catch (ParseException ex) {
            Logger.getLogger(TeDhenatEPuntorve.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void adresaIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adresaIDKeyTyped
        char c = evt.getKeyChar();
        
        if (!(Character.isDigit(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_adresaIDKeyTyped

    private void nrLeternjoftimitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nrLeternjoftimitKeyTyped
        char c = evt.getKeyChar();
        
        if (!(Character.isDigit(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
        }
        else if(nrLeternjoftimit.getText().length() == 9){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_nrLeternjoftimitKeyTyped

    private void shActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl4.getModel();
        model.setRowCount(0);
        trego_adresat("!@#","#@!");
        sh.setEnabled(false);
    }//GEN-LAST:event_shActionPerformed

    private void adresaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresaIDActionPerformed
     
    }//GEN-LAST:event_adresaIDActionPerformed

    private void Adresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adresa1ActionPerformed
    
    }//GEN-LAST:event_Adresa1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        AdresaRexhister ar = new AdresaRexhister();
        ar.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        pastro();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        KontaktetP kp = new KontaktetP();
        kp.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeDhenatEPuntorve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeDhenatEPuntorve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeDhenatEPuntorve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeDhenatEPuntorve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TeDhenatEPuntorve().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(TeDhenatEPuntorve.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adresa1;
    private javax.swing.JRadioButton F;
    private javax.swing.JRadioButton M;
    private javax.swing.JTextField adresaID;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dataLindjes;
    private javax.swing.JTextField email;
    private javax.swing.JTextField emri;
    private javax.swing.JTextField filter2;
    private javax.swing.JTextField filterRruga2;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField mbiemri;
    private javax.swing.JLabel mesazhZ;
    private javax.swing.JTextField nrLeternjoftimit;
    private javax.swing.JTextField nrTelefonit;
    private javax.swing.JButton sh;
    private javax.swing.JComboBox<String> statusi;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    private javax.swing.JTable tbl4;
    // End of variables declaration//GEN-END:variables
}
